title = "OpenTelemetry"
baseURL = "https://opentelemetry.io"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
font_awesome_version = "5.8.1"

[[params.fonts]]
name = "Roboto"
sizes = [300,400,600,700]
type = "sans_serif"

[[params.fonts]]
name = "Roboto Mono"
sizes = [400]
type = "monospace"