title = "OpenTelemetry"
baseURL = "https://opentelemetry.io"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
tagline = "Effective observability requires high-quality telemetry"
sub_tagline = "**OpenTelemetry** makes robust, portable telemetry a built-in feature of cloud-native software."
font_awesome_version = "5.8.1"
observability = """
The term [**observability**](https://en.wikipedia.org/wiki/Observability) stems from the discipline of [control theory](https://en.wikipedia.org/wiki/Control_theory) and refers to how well a system can be understood on the basis of the **telemetry** that it produces.

In software, observability typically refers to telemetry produced by **services** and is divided into three major verticals:

* [**Tracing**](https://opentracing.io/docs/overview/what-is-tracing), aka **distrbuted tracing**, provides insight into the full lifecycles, aka *traces*, of requests to the system, allowing you to pinpoint failures and performance issues.  
* [**Metrics**](https://opencensus.io/stats) provide quantitative information about processes running inside the system, including counters, gauges, and histograms. This domain also encompasses querying that data and configuring automated responses to quantitatively specified abormal states.
* [**Logging**](https://en.wikipedia.org/wiki/Log_file) provides insight into application-specific messages emitted by processes.

OpenTelemetry is an effort to combine all three verticals into a single set of system components and language-specific telemetry libraries. It is meant to replace both the [OpenTracing](https://opentracing.io) project, which focused exclusively on tracing, and the [OpenCensus](https://opencensus.io) project, which focused on tracing and metrics.

Intially, OpenTelemetry will not support logging. This vertical will be incorporated over time.
"""

[params.logos]
hero = "opentelemetry-horizontal-color.png"
cncf = "cncf.png"

[[menu.social]]
url = "https://github.com/open-telemetry/"
name = "GitHub"
identifier = "github"

[[menu.social]]
url = "https://twitter.com/opentelemetry"
name = "Twitter"
identifier = "twitter"

[[menu.social]]
url = "https://gitter.im/open-telemetry/community"
name = "Gitter"
identifier = "gitter"

[[params.fonts]]
name = "Noto Sans"
sizes = [300,400,600,700]
type = "sans_serif"
