title = "OpenTelemetry"
baseURL = "https://opentelemetry.io"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
tagline = "Effective observability requires high-quality telemetry"
sub_tagline = "**OpenTelemetry** makes robust, portable telemetry a built-in feature of cloud-native software."
font_awesome_version = "5.8.1"

[params.logos]
navbar = "opentelemetry-horizontal-white.png"
hero = "opentelemetry-horizontal-color.png"

[params.opencensus]
description = "Easily collect telemetry like metrics and distributed traces from your services"

[params.opentracing]
description = "Vendor-neutral APIs and instrumentation for distributed tracing"

[[menu.social]]
url = "https://github.com/open-telemetry/"
name = "GitHub"
identifier = "github"

[[menu.social]]
url = "https://twitter.com/OpenTelemetry"
name = "Twitter"
identifier = "twitter"

[[params.fonts]]
name = "Roboto"
sizes = [300,400,600,700]
type = "sans_serif"

[[params.fonts]]
name = "Roboto Mono"
sizes = [400]
type = "monospace"
